name: Lint

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run Prettier to format code
      run: npx prettier --write .
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -A
        git commit -m "Automate code formatting" --allow-empty
        git push
